### ISSUE TITLE
importing wrong model 

### ISSUE THREAD

**Issue by Riya922003** [Rohan-Gautam/Object-Detection-and-OCR#1]
model = YOLO("yolov9n.pt")

this code snnipet is using model yolo9n.pt but repo has yolo8n.pt 

corrected code should be 

model = YOLO("yolov8n.pt")

**Comment by Rohan-Gautam** [comment]
YOUR PULL REQUEST HAVE BEEN MERGED.
SEND ME YOUR GPAY ID I'LL GIVE YOU REWARD FOR THAT.
